# Author: Marc Gorzala
version: "3.9"
# see https://github.com/traefik/blog-posts/blob/master/2019_09_10-101_docker/docker-compose-07.yml
services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      #- "--certificatesresolvers.mytlschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.mytlschallenge.acme.email=${ACME_MAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${VOLUMES_LETSENCRYPT}:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
  show-dancer:
    image: ${SHOW_DANCER_IMAGE}
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.show-dancer.rule=Host(`${SHOW_DANCER_HOSTNAME}`)"
      - "traefik.http.routers.show-dancer.entrypoints=websecure"
      - "traefik.http.routers.show-dancer.tls=true"
      - "traefik.http.routers.show-dancer.tls.certresolver=mytlschallenge"
    depends_on:
      - traefik
