name: Build, Lint, and Test

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review

      - name: Run tests
        run: npm run test
