# Automatically check the code style for PRs, report findings as suggestions in PR
name: Lint

on: [pull_request]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
